### PR TITLE
Fix permission in install-deps.sh

### PR DESCRIPTION
**Pull request by cyrilloo**
Add sudo in last 2 commands:
virtualenv --system-site-packages -p python3 env
env/bin/pip install google-assistant-sdk[auth_helpers]==0.1.0 \
  grpc-google-cloud-speech-v1beta1==0.14.0 protobuf==3.1.0

### CODE REVIEW

**Comment by drigz** [comment]
These commands shouldn't be run as root - they create a virtual environment in the pi user's home directory.

Why do you want to run them with sudo?

**Comment by cyrilloo** [comment]
I face a permission issue while running this script, eventually my
configuration is wrong

2017-05-10 9:59 GMT+02:00 Rodrigo Queiro <notifications@github.com>:

**Comment by drigz** [comment]
Could you post the error you get, and also the output of the following commands?

```
cd ~/voice-recognizer-raspi  # or wherever you've cloned the repo
ls -l
id
```

**Comment by cyrilloo** [comment]
It appears there was no issue with the permission... thanks for support

**Pull request closed without merging**
