### PR TITLE
Use SOX play command for more beautiful voice

### PR DESCRIPTION
**Pull request by TimoCrafter**
Custom commands currently sound very metallic and not human. This pull request uses the SOX `play` command to play the generated `.wav` files. No filters are needed, the voice sounds much better.

### CODE REVIEW

**Comment by drigz** [comment]
@TimoCrafter, thanks for the PR!

I don't think we need to use `sox`, as the problem is more likely to be the filter than `aplay`. The filter was developed for a pre-production speaker (to avoid the exact problem it's causing now!) so maybe we need to change or remove it.

Could you compare these two alternatives on your speaker and let me know which sounds better?

1. Change `FILTER_B = np.array([1.75161639, ...` to `FILTER_B = 0.63 * np.array([1.75161639, ...`.
2. Change `player.play_bytes(eq_bytes, sample_rate=SAMPLE_RATE)` to `player.play_bytes(raw_bytes, sample_rate=SAMPLE_RATE)`.

2 should sound the same as your change with `sox` - let me know if it doesn't!

**Comment by TimoCrafter** [comment]
Using `0.63 * ...` makes the voice sound more beautiful, but it still sounds better with SOX.

Without using a filter, it doesn't sound better.

**Comment by drigz** [comment]
> Without using a filter, it doesn't sound better.

You mean that it sounds the same as originally? That's very surprising - can you double-check this?

**Comment by TimoCrafter** [comment]
It doesn't sound the same as originally, but it also sounds terrible. You can't say if better or worse, but different. Using SOX is definitely the most beautiful variant.

**Comment by drigz** [comment]
Sorry for taking so long to follow up on this - at the time I didn't have the right hardware to reproduce this.

For reference: I can confirm that it sounds much better with SoX. pico2wave is generating clipped audio files, which lead to horrible artifacts when they go through ALSA's rate conversion. SoX's rate conversion handles them much better. Additionally, there's no need for the equalization with production speakers.

I wish we could avoid pico2wave's clipping in the first place, but it's much easier to just use SoX.

@TimoCrafter, thanks for PR and testing the alternatives for me!

**Comment by ensonic** [comment]
FYI: one can also select a better resampler for alsa if that is the problem (e.g. in /etc/asound.conf)

    defaults.pcm.rate_converter "speexrate_medium"

**Comment by drigz** [comment]
For reference: I just tested ensonic's suggestion. All the speex converters have the same problem, although `defaults.pcm.rate_converter "samplerate"` does resolve the issue. For now, though, I'm happy to stick with SoX, as people will get it by pulling and don't have to reinstall `asound.conf`.

If we find any reason to drop the SoX dependency we can revisit.

**Pull request merged**
