### PR TITLE
Update info on HACKING.md

### PR DESCRIPTION
**Pull request by axilleas**
- Add a reference to HACKING.md in README.md for better discoverability.
- Add new subsection on installing the dependencies: `git` needs to be
  explicitly installed and the directory under which the repository must
  be cloned needs to be specific as it is hardcoded in some scripts.

### CODE REVIEW

**Comment by ensonic** [comment]
Thanks for updating the docs.

**Comment by drigz** [comment]
@axilleas, thanks for the PR! Could you let me know which scripts were failing due to the hardcoded directory? I'd like to make them directory-independent if possible.

**Comment by axilleas** [comment]
@drigz you're right, I tested again and I had no issues by using a different name for the directory. I must have messed up something the first time.

**Comment by drigz** [comment]
Yep, makes sense - your change should help avoid confusion there.

**Pull request merged**
