### PR TITLE
My mods

### PR DESCRIPTION
**Pull request by tvmk**

### CODE REVIEW

**Comment by tvmk** [comment]
i signed it

Regards.....TVM Krishna

**Comment by sheridat** [comment]
My understanding of the general approach by the owners of this repo is:
1. The repo is meant to be a basis for experimentation rather than as an alternative to a google home device;
2. The repo will be kept as "clean" as possible with only a few examples in src/action.py to show "experimenters" the general idea;
3. If "experimenters" want the functionality developed by others then the solution is to obtain the functionality from the repo that contains the desired functionality so for example if you want some of ktinkerer's /src/action.py you go copy it from his github repo. . Ktinkerer's web site contains all the information needed to implement the various amendments he has implemented http://ktinkerer.co.uk/list-mods-raspberry-pi-aiy-project/.

I haven't worked through the list of mods but don't some of these require additional packages etc to be installed. 

Ktinkerer's PR to shutdown/reboot has already been added to this repo.

**Comment by drigz** [comment]
@sheridat has it right. We're keeping this repo a relatively simple example. @tvmk, perhaps you could get in touch with Ktinkerer to let them know about your fork? Their contact details are in their blog post.

**Comment by tvmk** [comment]
Hey,

I just signed the petition "Ram Nath Kovind: JUSTICE FOR 9-MONTHS-OLD
INFANT RAPED" and wanted to see if you could help by adding your name.

Our goal is to reach 150,000 signatures and we need more support. You can
read more and sign the petition here:

http://chng.it/tsHWSpvsVx

Thanks!
TVM

**Pull request closed without merging**
