### PR TITLE
Add troubleshooting for #183

### PR DESCRIPTION
**Pull request by drigz**

### CODE REVIEW

**Comment by drigz** [comment]
@shivasiddharth: does this description make sense to you? @jrgleason: would it have helped you deal with the problem?

**Comment by shivasiddharth** [comment]
@drigz , but again on reboot, raspbian would have created a .asoundrc and would have populated it. So i would suggest asking people to copy the contents of asound.conf and pasting it into .asoundrc.

**Comment by drigz** [comment]
> but again on reboot

Do you know that it happens on reboot, or is it just a guess?

I'd really like to be able to reproduce the problem before adding a workaround to the repo, which is why I linked to the GitHub issue.

**Comment by shivasiddharth** [comment]
Not a guess, i have bumped into this N number of times and so have some of the users of my modified SDK project.

**Comment by shivasiddharth** [comment]
Here you go, another reference to this issue and the solution.. https://www.raspberrypi.org/forums/viewtopic.php?t=197039

**Comment by drigz** [comment]
Thanks for the other reference; I didn't realise it that other people were seeing it. Also, none of the other posts mention rebooting, which is why I was surprised to see it here.

**Pull request merged**
