### PR TITLE
Update to the Assistant API v1alpha2

### PR DESCRIPTION
**Pull request by drigz**
Also, fix some style issues from previous changes.

### CODE REVIEW

**Comment by mrbrooksatgoogle** [comment]
This is into the voicekit branch instead of aiyprojects. IIRC, that branch is deprecated.

**Comment by drigz** [comment]
Moved to internal pull request.

**Comment by deviantony** [comment]
FYI I was able to use the `drigz:upgrade-assistant` branch from drigz repository with some small tweaks to be abl to speak to the google assistant in French (using the `assistant_grpc_demo.py`). Great job @drigz ! Any chance to see this merged soon ?

**Comment by sheridat** [comment]
Hi, would you please share your "small tweaks"?

**Comment by deviantony** [comment]
@sheridat sure, they're available here: https://github.com/deviantony/aiyprojects-raspbian/tree/drigz-upgrade-assistant

Basically, I just changed a few things on top of the changes of @drigz:

* Hard-coded language code in `src/aiy/_apis_speech.py`: https://github.com/deviantony/aiyprojects-raspbian/commit/36ff4c706c2e92edf84c32c0eddd829eff4c027a#diff-1383c20cb543175d89154cde3b18efeeR102
* Moved `src/examples/voice/assistant_grpc_demo.py` to `src/assistant_grpc_demo.py`

Had to run `sudo pip install -r requirements.txt` to get the latest deps.

Note that this is just some dirty hacking but it seems to work well.

**Comment by sheridat** [comment]
@deviantony Thank You very much!

**Comment by Jaxom99** [comment]
Hello @deviantony I'm also trying to get some french speech recognition from the Google Assistant, using the AIY Kit and a RPi3. I cloned your repo, re-run the install scrips and everything, but the examples (including assistant_grpc_demo.py) still speak English.
Is there something I'm missing ? Thanks for your answer.

**Comment by deviantony** [comment]
@Jaxom99 have you installed the latest deps via `pip` ? My fork might be broken using the latest deps and I cannot try it at this time as I do not have access my AIY box.

**Comment by Jaxom99** [comment]
thanks for getting back @deviantony. Yes I used `sudo pip install -r requirements.txt` as you mentionned. But the i18n.py setting was still useless. Somebody advised to actually call `aiy.i18n.set_language_code('fr-FR')` in the beggining of the script...
Anyhow I went the easy way, reinstalled the provided image (from february) and used this setting : it speaks and recognize French ! But the "Hacking.md" way of use seems really broken.

**Pull request closed without merging**
